name: minitwitter
services:
  postgres_db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: supersecret123
      POSTGRES_DB: minitwitter
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
  
  post-api:
    image: chvvnl/my-first-docker-image
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:supersecret123@postgres_db:5432/minitwitter
      - command=/bin/sh -c "bunx drizzle-kit push && bun run prod"
    depends_on:
      - postgres_db